# Generated by Django 3.2.16 on 2023-01-18 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='favourite',
        ),
    ]
